laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Páginas restritas
    Route::group(['middleware' => ['auth.cadastro']], function() {
        Route::get('sobre', 'HomeController@sobre')->name('sobre');
        Route::get('dados-cadastrais', 'HomeController@dados')->name('dados');
        Route::patch('dados-cadastrais', 'HomeController@dadosPost')->name('dadosPost');
        Route::get('aulas', 'HomeController@aulas')->name('aulas');
        Route::get('aulas/{aula_slug}', 'HomeController@aula')->name('aulas.show');
        Route::get('aulas/{aula_slug}/duvidas', 'HomeController@aulaDuvidas')->name('aulas.duvidas');
        Route::get('aulas/{aula_id}/assistida', 'HomeController@aulaAssistida')->name('aulas.assistida');
        Route::post('aulas/{aula_id}/questao/{questao_id}', 'HomeController@aulaQuestaoPost')->name('aulas.questaoPost');
        Route::post('aulas/{aula_id}/duvida', 'HomeController@aulaDuvidaPost')->name('aulas.duvidaPost');
        Route::get('palestrantes', 'HomeController@palestrantes')->name('palestrantes');
        Route::get('certificado', 'CertificadoController@index')->name('certificado');
        Route::get('certificado/{aula_slug}', 'CertificadoController@emissao')->name('certificado.emissao');
    });

    // Login/Cadastro
    Route::get('login', 'CadastroAuth\AuthController@showLoginForm')->name('loginCadastro');
    Route::post('login', 'CadastroAuth\AuthController@login')->name('loginCadastroPost');
    Route::get('cadastro', 'CadastroAuth\AuthController@showRegistrationForm')->name('cadastro');
    Route::post('cadastro', 'CadastroAuth\AuthController@create')->name('cadastroPost');

    // Redefinição de Senha
    Route::get('esqueci-minha-senha', 'CadastroAuth\PasswordController@showLinkRequestForm')->name('esqueci');
    Route::post('esqueci-minha-senha', 'CadastroAuth\PasswordController@sendResetLinkEmail')->name('redefinicao');
    Route::get('redefinicao-de-senha/{token}', 'CadastroAuth\PasswordController@showResetForm')->name('redefinirForm');
    Route::post('redefinicao-de-senha', 'CadastroAuth\PasswordController@reset')->name('redefinir');

    // Logout
    Route::get('logout', 'CadastroAuth\AuthController@logout')->name('logoutCadastro');


    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::get('relatorio', 'RelatorioController@index')->name('painel.relatorio.index');
        Route::get('relatorio/{aulas}', 'RelatorioController@show')->name('painel.relatorio.show');
        Route::get('cadastros/exportar', 'CadastrosController@exportar')->name('painel.cadastros.exportar');
        Route::resource('cadastros', 'CadastrosController');
        Route::get('aulas/{aulas}/previa', 'AulasController@previa')->name('painel.aulas.previa');
        Route::put('aulas/aviso', 'AulasController@updateAviso')->name('painel.aulas.aviso');
        Route::get('aulas/{aulas}/teste-certificado', 'AulasController@certificado')->name('painel.aulas.certificado');
        Route::resource('aulas', 'AulasController');
        Route::resource('aulas.questoes', 'AulasQuestoesController');
        Route::resource('aulas.duvidas', 'AulasDuvidasController', ['except' => ['show', 'create', 'store']]);
		Route::resource('aulas.questoes.alternativas', 'AulasQuestoesAlternativasController');
		Route::resource('palestrantes', 'PalestrantesController');
		Route::resource('sobre-o-programa', 'SobreOProgramaController', ['only' => ['index', 'update']]);
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        // Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        // Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Aula.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\CropImage;
use Carbon\Carbon;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

use Illuminate\Support\Facades\Cache;

class Aula extends Model implements SluggableInterface
{
    use SluggableTrait;

    protected $sluggable = [
        'build_from' => 'titulo',
        'save_to'    => 'slug',
        'on_update'  => true
    ];

    protected $table = 'aulas';

    protected $guarded = ['id'];

    public static function boot()
    {
        parent::boot();

        self::created(function($model) {
            Cache::forget('aulas_count');
            return static::cachedCount();
        });

        self::deleted(function($model) {
            Cache::forget('aulas_count');
            return static::cachedCount();
        });
    }

    public static function cachedCount()
    {
        return Cache::rememberForever('aulas_count', function () {
            return static::count();
        });
    }

    public function scopeOrdenados($query)
    {
        return $query->orderBy('modulo', 'ASC')->orderBy('id', 'DESC');
    }

    public function setDataLiberacaoAttribute($date)
    {
        $this->attributes['data_liberacao'] = Carbon::createFromFormat('d/m/Y', $date)->format('Y-m-d');
    }

    public function getDataLiberacaoAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d', $date)->format('d/m/Y');
    }

    public function getIsAtivaAttribute()
    {
        $dataLiberacao = Carbon::createFromFormat('d/m/Y', $this->data_liberacao)
            ->startOfDay();

        return Carbon::now()->gte($dataLiberacao);
    }

    public function palestrante()
    {
        return $this->belongsTo(Palestrante::class, 'palestrante_id');
    }

    public function questoes()
    {
        return $this->hasMany(AulaQuestao::class, 'aula_id')->with('alternativas')->ordenados();
    }

    public function duvidas()
    {
        return $this->hasMany(AulaDuvida::class, 'aula_id')->ordenados();
    }

    public static function upload_moderadora_foto()
    {
        return CropImage::make('moderadora_foto', [
            'width'  => 130,
            'height' => 130,
            'path'   => 'assets/img/moderadoras/'
        ]);
    }

    public static function upload_capa()
    {
        return CropImage::make('capa', [
            'width'  => 375,
            'height' => 210,
            'path'   => 'assets/img/aulas/'
        ]);
    }

    public static function upload_certificado()
    {
        return CropImage::make('certificado', [
            'width'  => null,
            'height' => null,
            'path'   => 'assets/img/certificados/'
        ]);
    }

    public function adicionaProgresso($user)
    {
        $totalQuestoes = $this->questoes->count();

        $respostas = $user->respostas()
            ->with('alternativa')
            ->whereHas('questao.aula', function($q) {
                $q->where('id', $this->id);
            })->get();

        $totalRespondido   = $respostas->count();
        $respostasCorretas = $respostas->filter(function($resposta) {
            return $resposta->alternativa->alternativa_correta;
        })->count();

        if ($totalQuestoes > 0) {
            $respondida = $totalRespondido == $totalQuestoes;
            $porcentagemDeAcertos = round(($respostasCorretas / $totalQuestoes) * 100);
            $aptaAoCertificado = $porcentagemDeAcertos >= 75;
        } else {
            $respondida = false;
            $aptaAoCertificado = false;
        }

        $questionarioBloqueado = false;
        if ($respondida && ! $aptaAoCertificado) {
            $ultimaRespostaData = $respostas->sortByDesc('created_at')->first()->created_at;
            $horaAtual = Carbon::now();

            if ($horaAtual->lt($ultimaRespostaData->addHours(72))) {
                $questionarioBloqueado = true;
            } else {
                $respostas->each(function($resposta) {
                    $resposta->delete();
                });
                $respondida = false;
            }
        }

        $this->respondida = $respondida;
        $this->aptaAoCertificado = $aptaAoCertificado;
        $this->questionarioBloqueado = $questionarioBloqueado;

        return $this;
    }
}

laravel/app/Http/Controllers/Painel/AulasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AulasRequest;
use App\Http\Controllers\Controller;

use App\Models\Aula;
use App\Models\AulasAviso;
use App\Models\Palestrante;

class AulasController extends Controller
{
    public function index()
    {
        $registros = Aula::ordenados()->get();
        $aviso = AulasAviso::first()->aviso;

        return view('painel.aulas.index', compact('registros', 'aviso'));
    }

    public function updateAviso(Request $request)
    {
        $aviso = AulasAviso::first();

        $aviso->aviso = $request->aviso;
        $aviso->save();

        return redirect()->route('painel.aulas.index')->with('success', 'Aviso salvo com sucesso.');
    }

    public function create()
    {
        $palestrantes = Palestrante::ordenados()->lists('nome', 'id');

        return view('painel.aulas.create', compact('palestrantes'));
    }

    public function store(AulasRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Aula::upload_capa();
            if (isset($input['certificado'])) $input['certificado'] = Aula::upload_certificado();
            if (isset($input['moderadora_foto'])) $input['moderadora_foto'] = Aula::upload_moderadora_foto();

            Aula::create($input);

            return redirect()->route('painel.aulas.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Aula $registro)
    {
        $palestrantes = Palestrante::ordenados()->lists('nome', 'id');

        return view('painel.aulas.edit', compact('registro', 'palestrantes'));
    }

    public function update(AulasRequest $request, Aula $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Aula::upload_capa();
            if (isset($input['certificado'])) $input['certificado'] = Aula::upload_certificado();
            if (isset($input['moderadora_foto'])) $input['moderadora_foto'] = Aula::upload_moderadora_foto();

            $registro->update($input);

            return redirect()->route('painel.aulas.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Aula $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.aulas.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

    public function certificado(Aula $aula)
    {
        $user = new \stdClass();
        $user->nome = 'Teste de Certificado';

        $dompdf = new \Dompdf\Dompdf();
        $dompdf->loadHtml(view(
            'frontend.certificado-pdf', compact('user', 'aula')
        )->render());
        $dompdf->setPaper('A4', 'landscape');
        $dompdf->render();
        $dompdf->stream("AccordAcademy_Certificado-Modulo{$aula->modulo}.pdf");
    }

    public function previa(Aula $aula)
    {
        $duvidas = [];
        $user    = new \App\Models\Cadastro;

        echo '<h1 style="text-align:center;color:red;background:#fff;margin:0;padding:1em;">PRÉVIA DA VISUALIZAÇÃO DA AULA</h1>';

        return view('frontend.aula', compact('aula', 'duvidas', 'user'));
    }
}

laravel/resources/views/painel/aulas/duvidas/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Aulas / {{ $aula->titulo }} /</small> {{ $registro->resposta ? 'Editar' : 'Responder' }} dúvida</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.aulas.duvidas.update', $aula->id, $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.aulas.duvidas.form', ['submitText' => 'Salvar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/aulas/duvidas/form.blade.php
@include('painel.common.flash')

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::label('cadastro', 'Usuário') !!}
            {!! Form::text('cadastro', $registro->cadastro->nome, ['class' => 'form-control', 'disabled']) !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::label('enviada_em', 'Enviada em') !!}
            {!! Form::text('enviada_em', $registro->created_at->format('d/m/Y | H:i\h'), ['class' => 'form-control', 'disabled']) !!}
        </div>
    </div>
</div>

<div class="form-group">
    {!! Form::label('duvida', 'Dúvida') !!}
    {!! Form::textarea('duvida', null, ['class' => 'form-control', 'style' => 'resize:none;height:150px']) !!}
</div>

<div class="form-group">
    {!! Form::label('resposta', 'Resposta') !!}
    {!! Form::textarea('resposta', null, ['class' => 'form-control', 'style' => 'resize:none;height:150px']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.aulas.duvidas.index', [$aula->id, 'filtro' => ($registro->resposta ? 'respondidas' : 'em-aberto')]) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/aulas/duvidas/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.aulas.index') }}" title="Voltar para Aulas" class="btn btn-sm btn-default">
        &larr; Voltar para Aulas
    </a>

    <legend>
        <h2>
            <small>Aulas / {{ $aula->titulo }} /</small> Dúvidas
        </h2>
    </legend>

    <div class="btn-group">
        <a href="{{ route('painel.aulas.duvidas.index', [$aula->id, 'filtro' => 'em-aberto']) }}" class="btn btn-info @if(request('filtro') != 'respondidas') active @endif">Em aberto</a>
        <a href="{{ route('painel.aulas.duvidas.index', [$aula->id, 'filtro' => 'respondidas']) }}" class="btn btn-info @if(request('filtro') == 'respondidas') active @endif">Respondidas</a>
    </div>

    <hr>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info">
        <thead>
            <tr>
                <th>Usuário</th>
                <th>Dúvida</th>
                <th>Enviada em</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>{{ $registro->cadastro->nome }}</td>
                <td>
                    {{ $registro->duvida }}
                    @if($registro->resposta)
                    <hr style="margin:8px 0">
                    <small><strong>{{ $registro->resposta }}</strong></small>
                    @endif
                </td>
                <td style="white-space: nowrap">{{ $registro->created_at->format('d/m/Y | H:i\h') }}</td>
                <td class="crud-actions" style="width:215px">
                    {!! Form::open([
                        'route'  => ['painel.aulas.duvidas.destroy', $aula->id, $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.aulas.duvidas.edit', [$aula->id, $registro->id]) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>
                            {{ $registro->resposta ? 'Editar' : 'Responder' }}
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {!! $registros->appends($_GET)->render() !!}
    @endif

@endsection